import Phaser from 'phaser';

export const GAME_WIDTH = 480;
export const GAME_HEIGHT = 270;

export const TUNING = {
  fadeMs: 250,
  worldGravity: 600,
  boardSkewPx: 0,
  useGridBarrel: true,
  useGridBoss: true,
  dropRodOnHit: false,
  player: {
    width: 18,
    height: 28,
    runSpeed: 110,
    jumpVelocity: -260,
    hp: 3,
    invulnerabilityMs: 1000,
  },
  interaction: {
    radius: 54,
  },
  dialogue: {
    typewriterCharMs: 18,
  },
  barrelMan: {
    speeds: {
      slow: 35,
      normal: 55,
      burst: 75,
      hesitate: 0,
    },
    behaviorChangeMs: {
      min: 700,
      max: 1400,
    },
    exposedSpeedMultiplier: 0.45,
    exposureToPlantSeconds: 3,
    exposureDecayPerSecond: 1,
    rngSeed: 41473,
  },
  barrelScene: {
    worldWidth: 1200,
    groundY: 246,
    playerStartX: 64,
    playerStartY: 198,
    barrelStartX: 132,
    barrelStartY: 230,
    slideX: 1048,
    slideExitX: 1135,
    plantRestartDelayMs: 900,
    shadeAlpha: 0.24,
    lightAlpha: 0.22,
    shadowLengthMultiplier: 0.72,
    shadowHeight: 8,
    shadowYOffset: 2,
    barrelRollSpeedX: 68,
    barrelRollSlope: 0.16,
    barrelRollRotationSpeed: 4.2,
  },
  barrelGridScene: {
    tileW: 32,
    tileH: 20,
    boardOriginX: 16,
    boardOriginY: 80,
    boardSkewPx: 0,
    heroGridSpeed: 3.4,
    barrelGridSpeeds: {
      slow: 1.1,
      normal: 1.7,
      burst: 2.3,
      hesitate: 0,
    },
    barrelWobble: 0.15,
    shadowHalfSize: 0.55,
    plantRestartDelayMs: 1500,
  },
  golfIntroScene: {
    groundY: 226,
    golferX: 88,
    actorY: 226,
    heroX: 342,
    holeX: 372,
    ballStartX: 106,
    ballStartY: 221,
    backswingAtMs: 900,
    swingAtMs: 1700,
    ballFlightMs: 1550,
    bonkPauseMs: 450,
    dropMs: 1250,
    totalMs: 6100,
  },
  illusionScene: {
    worldWidth: 540,
    groundY: 246,
    playerStartX: 56,
    playerStartY: 198,
    meditatorX: 160,
    meditatorY: 230,
    wallX: 444,
    wallY: 70,
    wallWidth: 32,
    wallHeight: 176,
    wallRightEdge: 470,
    doorY: 246,
    doorXs: [218, 278, 338, 398],
  },
  bossScene: {
    worldWidth: 720,
    groundY: 246,
    playerStartX: 60,
    playerStartY: 198,
    slabX: 520,
    slabY: 246,
    robotStartX: 704,
    robotStopX: 620,
    robotMinX: 555,
    robotMaxX: 676,
    worshipperXs: [462, 492, 522, 552, 582],
    damageKnockbackX: 150,
    damageKnockbackY: -120,
    hitStunMs: 180,
    footDoorOffsetX: -20,
    footDoorOffsetY: -24,
    cablePulseMs: 520,
    fightStartDelayMs: 450,
  },
  bossArenaScene: {
    tileW: 32,
    tileH: 20,
    originX: 16,
    originY: 100,
    arenaMinGx: 0,
    arenaMaxGx: 14,
    arenaMinGy: 0,
    arenaMaxGy: 7,
    heroEntranceStartGx: -0.8,
    heroStartGx: 1.5,
    heroStartGy: 3.5,
    altarGx: 7,
    altarGy: 3.5,
    altarRadius: 0.7,
    rodSpawnPoints: [
      { gx: 2.0, gy: 1.2 },
      { gx: 4.0, gy: 6.2 },
      { gx: 12.5, gy: 5.8 },
    ],
    robotStartGx: 15.5,
    robotIntroStopGx: 11,
    robotFightGx: 5,
    robotFightGy: 4,
    robotMinGx: 1,
    robotMaxGx: 13,
    robotMinGy: 1.5,
    robotMaxGy: 6.5,
    robotChaseSpeed: 1.2,
    kickRangeX: 2.0,
    kickRangeY: 0.7,
    laserCooldownMs: 2500,
    laserWindupMs: 700,
    laserRadius: 0.7,
    robotStumbleMs: 1200,
    escalationSpeedMul: 1.2,
    escalationCooldownMul: 0.8,
    pickupRange: 0.7,
    strikeRange: 1.2,
    rodRespawnMs: 3000,
  },
  endingScene: {
    stageY: 176,
    groundY: 246,
    actorY: 190,
    heroX: 240,
    barrelStartX: -28,
    barrelEndX: 162,
    meditatorStartX: 508,
    meditatorEndX: 318,
    barrelWalkMs: 1550,
    meditatorWalkMs: 1750,
    danceStartMs: 2000,
  },
  robot: {
    walkSpeed: 30,
    kickRange: 70,
    kickWindupMs: 500,
    kickActiveMs: 200,
    kickRecoverMs: 600,
    laserWindupMs: 600,
    laserProjectileSpeed: 180,
    idleBetweenAttacksMs: 800,
    walkMs: 900,
  },
  testScene: {
    groundY: 246,
    playerStartX: 72,
    playerStartY: 198,
    npcX: 214,
    npcY: 230,
    wallX: 320,
    wallY: 218,
    wallWidth: 18,
    wallHeight: 56,
  },
} as const;

const search = new URLSearchParams(window.location.search);
export const RECORD_MODE = search.get('record') === '1';

export const PHASER_CONFIG: Phaser.Types.Core.GameConfig = {
  type: Phaser.AUTO,
  parent: 'game',
  backgroundColor: '#111421',
  pixelArt: true,
  antialias: false,
  roundPixels: true,
  scale: {
    width: GAME_WIDTH,
    height: GAME_HEIGHT,
    mode: RECORD_MODE ? Phaser.Scale.NONE : Phaser.Scale.FIT,
    autoCenter: Phaser.Scale.CENTER_BOTH,
    zoom: RECORD_MODE ? 4 : 1,
  },
  physics: {
    default: 'arcade',
    arcade: {
      gravity: { x: 0, y: TUNING.worldGravity },
      debug: false,
    },
  },
};
